baseURL: https://paclema.com/
languageCode: en-us
defaultContentLanguage: "en"
title: paclema


module:
  imports:
    - path: github.com/imfing/hextra

# Parse Git commit
enableGitInfo: true

menu:
  main:
    - name: Projects
      url: /projects/
      weight: 1
    # - name: Recipes
    #   url: /recipes/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
    - name: Search
      params:
        type: search

  # sidebar:
  #   - identifier: more
  #     name: More
  #     params:
  #       type: separator
  #     weight: 1
  #   - identifier: about
  #     name: "About"
  #     pageRef: "/about"
  #     weight: 2
  #   - identifier: hugoDocs
  #     name: "Hugo Docs ↗"
  #     url: "https://gohugo.io/documentation/"
  #     weight: 3


markup:
  highlight:
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      table: true
      taskList: true
    renderer:
      unsafe: true
  extensions:
    admonition: true


params:
  page:
    # full (100%), wide (90rem), normal (1280px)
    width: wide
  theme:
    # light | dark | system
    default: light
    displayToggle: true
  footer:
    enable: true
    displayCopyright: true
    displayPoweredBy: true
    width: normal
    customText: "© 2025 paclema.com"
  # Display the last modification date
  displayUpdatedDate: true
  dateFormat: "January 2, 2006"
  # Search
  # flexsearch is enabled by default
  search:
    enable: true
    type: flexsearch
  toc:
    displayTags: true
  highlight:
    copy:
      enable: true
      # hover | always
      display: hover
  navbar:
    displayTitle: true
    displayLogo: false

privacy:
  instagram:
    disable: false
    simple: true